blank_issues_enabled: false

contact_links:
  - name: Discussion
    url: https://github.com/gonzalezreal/textual/discussions
    about: Textual Q&A, ideas, and feature requests
  - name: Documentation
    url: https://swiftpackageindex.com/gonzalezreal/textual/main/documentation/textual
    about: Read documentation for Textual
